### ISSUE TITLE
Hello author, I am very interested in your paper, but I have a problem in reproducing the code

### ISSUE THREAD

**Issue by 2081147463** [zhangxinyu-xyz/ISE-ReID#1]
I use a nvidia 2080ti 
batch size 64
lr 0.000175
However, the final results did not reach the optimal results of the paper。
best mAP 75.1%
CMC Scores:
  top-1        89.074%
  top-5        95.695%
  top-10       97.298%
I hope you can give me a little help。Thanks!

**Comment by zhangxinyu-xyz** [comment]
> I use a nvidia 2080ti batch size 64 lr 0.000175 However, the final results did not reach the optimal results of the paper。 best mAP 75.1% CMC Scores: top-1 89.074% top-5 95.695% top-10 97.298% I hope you can give me a little help。Thanks!

Hi, the number of GPUs is sensitive in ReID tasks. The reason may be the batch size for BN. We follow ClusterContrast to use 4 GPUs and 256 images in a batch. I recommend using this setting to reproduce the results.
